# Generated by Django 3.2.4 on 2021-06-29 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='newuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='next_of_kin_phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
