# Generated by Django 3.2.4 on 2021-06-29 04:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210629_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='next_of_kin_phone_number',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='phone_number',
            field=models.CharField(max_length=200),
        ),
    ]
