# Generated by Django 3.2.4 on 2021-06-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_newuser_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='bitcoin_wallet_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='next_of_kin',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='referral_code',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
