# Generated by Django 3.2.4 on 2021-07-06 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210706_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='newuser',
            old_name='is_admin',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='newuser',
            old_name='is_staff',
            new_name='staff',
        ),
    ]
