# Generated by Django 3.2.4 on 2021-07-08 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_newuser_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='newuser',
            old_name='admin',
            new_name='is_admin',
        ),
        migrations.RenameField(
            model_name='newuser',
            old_name='staff',
            new_name='is_staff',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='timestamp',
        ),
    ]
